import { Inter } from "next/font/google";
import "./globals.css";
import "./settings.css";
import { ClerkProvider } from "@clerk/nextjs";
import { esES } from "@clerk/localizations";
import "react-toastify/dist/ReactToastify.css";
import Providers from "@/providers/providers";
import { Drawer } from "@/components/ui/drawer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Card Quest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider localization={esES}>
      <html lang="es" translate="no">
        <body className={inter.className}>
          <Providers>
            <Drawer>{children}</Drawer>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
