import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

import "react-toastify/dist/ReactToastify.css";
import { Raleway } from "next/font/google";

import Providers from "@/providers/providers";
import { Drawer } from "@/components/ui/drawer";
import "./globals.css";

const inter = Raleway({ subsets: ["latin"] });

export const metadata = {
  title: "Harem: Project Maid",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        variables: {
          colorPrimary: "white",
        },
        layout: {
          socialButtonsPlacement: "bottom",
          socialButtonsVariant: "iconButton",
        },
        baseTheme: dark,
      }}
    >
      <html lang="en" translate="no">
        <body className={inter.className}>
          <Providers>
            <Drawer direction="left" shouldScaleBackground>
              {children}
            </Drawer>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
