import { Inter } from "next/font/google";
import "./globals.css";
import "./settings.css";
import { ClerkProvider } from "@clerk/nextjs";
import { esES } from "@clerk/localizations";
import "react-toastify/dist/ReactToastify.css";
import Providers from "@/providers/providers";
import { Drawer } from "@/components/ui/drawer";

import { dark } from "@clerk/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Card Quest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      // localization={esES}
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en" translate="no">
        <body className={inter.className}>
          <Providers>
            <Drawer direction="left" shouldScaleBackground>
              {children}
            </Drawer>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
